lang: en-US
title: The Wheel Deal
description: "FIRST LEGO League Robotics Team #41927 - The Wheel Deal"
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
exclude:
  - Gemfile
  - .gitignore
  - .jekyll-cache
github:
  is_project_page: true
